// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnulgzgaLmh4yeQXLhO3fXai4dkqlidXk',
    appId: '1:638387293513:web:3f94bb6637843617ee5e98',
    messagingSenderId: '638387293513',
    projectId: 'yans-59f25',
    authDomain: 'yans-59f25.firebaseapp.com',
    storageBucket: 'yans-59f25.appspot.com',
    measurementId: 'G-63NSS1C55X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2y3CrV-e62upPNIw84w6fm3382hWfiKQ',
    appId: '1:638387293513:android:84f90841d4cbc1baee5e98',
    messagingSenderId: '638387293513',
    projectId: 'yans-59f25',
    storageBucket: 'yans-59f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWc_utXhOn5ZsMcqkZAdoWzx2zZtAVlg',
    appId: '1:638387293513:ios:5b98edda955d8c38ee5e98',
    messagingSenderId: '638387293513',
    projectId: 'yans-59f25',
    storageBucket: 'yans-59f25.appspot.com',
    iosClientId:
        '638387293513-8ra68dk623evgac977tie4ip8svdno8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.yans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwWc_utXhOn5ZsMcqkZAdoWzx2zZtAVlg',
    appId: '1:638387293513:ios:5b98edda955d8c38ee5e98',
    messagingSenderId: '638387293513',
    projectId: 'yans-59f25',
    storageBucket: 'yans-59f25.appspot.com',
    iosClientId:
        '638387293513-8ra68dk623evgac977tie4ip8svdno8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.yans',
  );
}
